# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    environment:
      PYTHONPATH=./src
    steps: 
      - checkout
      - python/load-cache
      - python/install-deps
      - run:
          command: ./manage.py test
          name: test

workflows:
  main:
    jobs:
      - build-and-test
